### ISSUE TITLE
NEW FEATURE: Allow to add formatoption presets

### ISSUE THREAD

**Issue by Chilipp** [psyplot/psy-view#3]
#### Summary
It should be able to import/export presets, i.e. YAML-formatted mappings from formatoption key to value

#### Reason
This allows to customize the plot easily for recurring tasks or data files.

#### Detailed explanation
A preset file should look like

```yaml
title: "{desc}"
mapplot:
  projection: "ortho"
lineplot:
  color: "k"
```
