### ISSUE TITLE
Error when clicking the refresh button after animation

### ISSUE THREAD

**Issue by Chilipp** [psyplot/psy-view#55]
#### Problem description

When making an animation and clicking the refresh button, one gets the following error (see Screencast below)

```
Traceback (most recent call last):
File "/home/psommer/Documents/code/development/psyplot/psy-view/psy_view/ds_widget.py", line 333, in reload
num = next(num for num, f in sp.dsnames_map.items() if f == fname)
StopIteration
```

https://user-images.githubusercontent.com/9960249/116358339-d3635900-a7fd-11eb-87ea-7ec913d6e811.mp4

#### Output of ``psyplot -aV``

<details>
```
psy_maps.plugin:
  requirements:
    cartopy: 0.18.0
  version: 1.3.2+2.g26b6411.dirty
psy_reg.plugin:
  requirements:
    scipy: 1.5.3
    statsmodels: 0.12.2
  version: 1.3.0+3.gc849e50
psy_simple.plugin:
  version: 1.3.1
psy_strat.plugin:
  version: 0.1.0
psy_transect.plugin:
  version: 0.0.1.dev0
psyplot:
  requirements:
    matplotlib: 3.4.1
    numpy: 1.20.2
    pandas: 1.2.3
    python: 3.8.6 | packaged by conda-forge | (default, Oct  7 2020, 19:08:05)  [GCC
      7.5.0]
    xarray: 0.17.0
  version: 1.3.1
psyplot_gui:
  requirements:
    pyqt: 5.12.3
    qt: 5.12.9
    qtconsole: 5.0.3
  version: 1.3.0

```

</details>
