### ISSUE TITLE
Suspicious result when using plot2d for R02B04 ICON output

### ISSUE THREAD

**Issue by leuty** [psyplot/psy-view#59]
#### Problem description

Hi Philipp

A ncview-like tool for unstructured ICON grids would be so awesome. Thx for the work.

I am currently using psy-view on the output of the first timesteps of a global ICON R02B04 aquaplanet. You can download the file here:
https://polybox.ethz.ch/index.php/s/jOCwUmebnzYDc4f

Most fields look ok, except `sob_s` and `sob_t` when using plot2d. I suspect something goes wrong with the grid.

![psy-view](https://user-images.githubusercontent.com/14977216/173072649-f4162e54-8972-42b7-a36a-389d6a7e0962.png)

Note that these are my first baby steps into psyplot. It is thus likely that I am doing something wrong. My primary reason for reporting this is that you explicitly solicit feedback :-)

#### Expected Output
I've visualized the same field in Paraview (CDI plugin). There the structure is ok, so I don't think the problem lies with ICON.
![Paraview](https://user-images.githubusercontent.com/14977216/173073658-2b968242-2bfc-42b5-9081-f46decebf66e.png)

#### Output of ``psyplot -aV``

<details>

```
psy_maps.plugin:
  requirements:
    cartopy: 0.20.2
  version: 1.4.2
psy_simple.plugin:
  version: 1.4.1
psyplot:
  requirements:
    matplotlib: 3.5.2
    numpy: 1.20.1
    pandas: 1.2.4
    python: 3.9.4 (default, Aug 13 2021, 12:30:13)  [GCC 8.1.0 20180502 (Cray Inc.)]
    xarray: 2022.3.0
  version: 1.4.2
psyplot_gui:
  requirements:
    pyqt: 5.15.6
    qt: 5.15.2
    qtconsole: 5.3.1
  version: 1.4.0
```
</details>
